codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 0
  round: nearest
  range: "70...95"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "tox/_verlib.py"  # vendored in and not internally tested
  - "tox/__main__.py"
