repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.11.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
        exclude: "^(src/tox/util/pep517/backend.py|tests/demo_pkg_inline/build.py)$"
      - id: pyupgrade
        files: "^(src/tox/util/pep517/backend.py|tests/demo_pkg_inline/build.py)$"
  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args:
          - --safe
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt
        args:
          - --min-py3-version
          - "3.6"
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "0.5.0"
    hooks:
      - id: tox-ini-fmt
        args: [ "-p", "fix" ]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==20.8b1
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: rst-backticks
  - repo: local
    hooks:
      - id: changelogs-rst
        name: changelog filenames
        language: fail
        entry: "changelog files must be named ####.(feature|bugfix|doc|removal|misc).rst"
        exclude: ^docs/changelog/(\d+\.(feature|bugfix|doc|removal|misc).rst|README.rst|template.jinja2)
        files: ^docs/changelog/
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        additional_dependencies:
        - flake8-bugbear==21.4.3
        - flake8-comprehensions==3.4
        - flake8-pytest-style==1.4.1
        - flake8-spellcheck==0.24
        - flake8-unused-arguments==0.0.6
