sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev
  - nightly
  - pypy
env:
  TOXENV=py

matrix:
  fast_finish: true
  allow_failures:
  - os:  osx
  - python: 3.7-dev
  - python: nightly
  - python: pypy
  include:
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=fix-lint
    - os: osx
      language: generic

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source .travis-osx; fi
 # work around https://github.com/travis-ci/travis-ci/issues/8363
 - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then pyenv global system 3.5; fi

install:
  - pip install -U six
  - pip install --pre -U tox

script:
  - tox

after_success:
  - if [[ $TOXENV == "py" ]]; then tox -e coverage,codecov; fi
