trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - tasks/*

phases:
- phase: 'Test'
  queue:
    name: 'Hosted Linux Preview'
    parallel: 4
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: pip install -U tox
    displayName: 'install tox'
  - script: tox -e py
    displayName: 'run tests'
  - task: PublishTestResults@2
    displayName: publish test results
    inputs:
      testResultsFiles: '.tox/test-results.*.xml'
    condition: always()
  - script: echo hello world
