image: "Visual Studio 2015"

build: false  # Not a C# project

only_commits: # we only run tests here, so only trigger if we modify the source files or the config
  files:
  - src/**/*
  - tests/**/*
  - appveyor.yml
  - setup.py
  - tox.ini
  - pyproject.toml
  - MANIFEST.in
  - setup.cfg
  - .travis.yml
  - CHANGELOG.rst
  # this final one acts as proxy for release commits

environment:
  matrix:
  - TOXENV: py27
  - TOXENV: py34
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

matrix:
  fast_finish: true

install:
- C:\Python37\python -m pip install --pre -U tox

test_script:
- C:\Python37\scripts\tox

after_test:
- C:\Python37\scripts\tox -e coverage,codecov

cache:
- '%LOCALAPPDATA%\pip\cache'
- '%USERPROFILE%\.cache\pre-commit'
