name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
  - repository: tox
    type: github
    endpoint: toxdevorg
    name: tox-dev/azure-pipelines-template
    ref: master

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/*
pr:
  branches:
    include:
    - master

variables:
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  PYTEST_XDIST_PROC_NR: 'auto'

jobs:
- template: run-tox-env.yml@tox
  parameters:
    tox_version: ''
    jobs:
      fix_lint: null
      docs: null
      package_description: null
      dev: null
      py37:
        before:
        - script: py.exe -0
        image: [linux, windows, macOs]
      py36:
        image: [linux, windows, macOs]
      py35:
        image: [linux, windows, macOs]
      py34:
        image: [linux, windows, macOs]
      py27:
        image: [linux, windows, macOs]
    env:
    - key: [py27, py34, py35, py36, py37]
      coverage: 'coverage'

- template: merge-coverage.yml@tox
  parameters:
    dependsOn: [py27, py34, py35, py36, py37]

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - template: publish-pypi.yml@tox
    parameters:
    - external_feed: 'toxdev'
    - pypi_remote: 'pypi-toxdev'
    - dependsOn:
      - check
      - report_coverage
