name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)
resources:
  repositories:
  - repository: tox
    type: github
    endpoint: toxdevorg
    name: tox-dev/azure-pipelines-template
    ref: master

trigger:
  batch: true
  branches:
    include:
    - master
    - rewrite
    - refs/tags/*
pr:
  branches:
    include:
    - master
    - rewrite

variables:
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"

jobs:
- template: run-tox-env.yml@tox
  parameters:
    jobs:
      fix_lint: null
      docs: null
      dev: null
      pkg_meta: null
      py39:
        image: [linux]
      py38:
        image: [linux, windows, macOs]
      py37:
        image: [linux, windows, macOs]
      py36:
        image: [linux, windows, macOs]
      py35:
        image: [linux, windows, macOs]
      pypy3:
        image: [linux, windows, macOs]
    coverage:
      with_toxenv: 'cov' # generate .tox/.coverage, .tox/coverage.xml after test run
      for_envs:
      - py39
      - py38
      - py37
      - py36
      - py35
      - pypy3

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - template: publish-pypi.yml@tox
    parameters:
      external_feed: 'toxdev'
      pypi_remote: 'pypi-toxdev'
      dependsOn:
      - fix_lint
      - docs
      - dev
      - pkg_meta
      - report_coverage
