name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

resources:
  repositories:
  - repository: tox
    type: github
    endpoint: toxdevorg
    name: tox-dev/azure-pipelines-template
    ref: master

trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/*
pr:
  branches:
    include:
    - master

variables:
  PYTEST_ADDOPTS: "-v -v -ra --showlocals"
  PYTEST_XDIST_PROC_NR: 'auto'

jobs:
- template: run-tox-env.yml@tox
  parameters:
    jobs:
      check:
        py: '3.7'
        toxenvs:
        - fix_lint
        - docs
        - package_description
      windows:
        coverage: 'coverage'
        toxenvs:
        - py37
        - py36
        - py35
        - py34
        - py27
      linux:
        coverage: 'coverage'
        toxenvs:
        - py38
        - py37
        - py36
        - py35
        - py34
        - py27
      macOs:
        coverage: 'coverage'
        toxenvs:
        - py37
        - py27
- template: merge-coverage.yml@tox
  parameters:
    dependsOn:
    - windows
    - linux
    - macOs

- ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
  - template: publish-pypi.yml@tox
    parameters:
    - external_feed: 'toxdev'
    - pypi_remote: 'pypi-toxdev'
    - dependsOn:
      - check
      - report_coverage
