[tool.towncrier]
    package = "tox"
    filename = "CHANGELOG.rst"
    directory = "tox/changelog"
    template = "tox/changelog/template.jinja2"
    title_format = "{version} ({project_date})"
    issue_format = "`#{issue} <https://github.com/tox-dev/tox/issues/{issue}>`_"
    pr_format = "`pr{issue} <https://github.com/tox-dev/tox/pull/{issue}>`_"
    underlines = ["=", "-"]

    [[tool.towncrier.section]]
        path = ""

    [[tool.towncrier.format]]
        kind = "issue"
        patterns = ["issue(\\d)", "(\\d)"]
        format = "`#{id} <https://github.com/tox-dev/tox/issues/{id}>`_"

    [[tool.towncrier.format]]
        kind = "pull request"
        patterns = ["pr(\\d)", "pull-request(\\d)"]
        format = "`#{id} <https://github.com/tox-dev/tox/pull/{id}>`_"

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "breaking"
        name = "Backward incompatible changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Documentation improvements"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Miscellaneous / trivial changes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "deprecation"
        name = "Deprecations (removal in next major release)"
        showcontent = true
